using System;
using Microsoft.EntityFrameworkCore.Migrations;

namespace private_sale.Migrations
{
    public partial class ModifySaleAndIdAutoGenerated : Migration
    {
        protected override void Up(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.AlterColumn<DateTime>(
                name: "StartAt",
                table: "Sale",
                type: "datetime2",
                nullable: true,
                oldClrType: typeof(DateTime),
                oldType: "datetime2");

            migrationBuilder.AlterColumn<DateTime>(
                name: "EndAt",
                table: "Sale",
                type: "datetime2",
                nullable: true,
                oldClrType: typeof(DateTime),
                oldType: "datetime2");

            migrationBuilder.AddColumn<Guid>(
                name: "BrandId",
                table: "ProductInformation",
                type: "uniqueidentifier",
                nullable: true);

            migrationBuilder.CreateIndex(
                name: "IX_ProductInformation_BrandId",
                table: "ProductInformation",
                column: "BrandId");

            migrationBuilder.AddForeignKey(
                name: "FK_ProductInformation_Brand_BrandId",
                table: "ProductInformation",
                column: "BrandId",
                principalTable: "Brand",
                principalColumn: "Id",
                onDelete: ReferentialAction.Restrict);
        }

        protected override void Down(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.DropForeignKey(
                name: "FK_ProductInformation_Brand_BrandId",
                table: "ProductInformation");

            migrationBuilder.DropIndex(
                name: "IX_ProductInformation_BrandId",
                table: "ProductInformation");

            migrationBuilder.DropColumn(
                name: "BrandId",
                table: "ProductInformation");

            migrationBuilder.AlterColumn<DateTime>(
                name: "StartAt",
                table: "Sale",
                type: "datetime2",
                nullable: false,
                defaultValue: new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                oldClrType: typeof(DateTime),
                oldType: "datetime2",
                oldNullable: true);

            migrationBuilder.AlterColumn<DateTime>(
                name: "EndAt",
                table: "Sale",
                type: "datetime2",
                nullable: false,
                defaultValue: new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                oldClrType: typeof(DateTime),
                oldType: "datetime2",
                oldNullable: true);
        }
    }
}
